# Shared configuration for ALL FinFlow microservices
# File: application.yml (root of config repo)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

logging:
  level:
    root: INFO
    com.finflow: DEBUG
    org.springframework.cloud: INFO
