server:
  port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/Pavankumar1221/finflow-config-repo.git
          default-label: main
          clone-on-start: true
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
